Docker: improve caching, exclude more from build context, allow external RPC connections (#828)
* BROKEN: rewrite dockerfile for improved caching

- build stage depends on an image which already has Rust present
- perform all stage-initalization steps before copying any data,
  preserving maximum caching
- build all deps in a separate cached stage so changes only require
  rebuilding the affected code
- build each module independently in reverse topo order so unaffected
  build stages can in principle retain their cache

Unfortunately, the steps above still don't work: despite the presence
of log lines like

```
 ---> 104821d12748
Step 32/54 : RUN cargo build --$PROFILE -p polkadot-primitives
 ---> Running in a78deef9950c
    Finished release [optimized] target(s) in 0.97s
Removing intermediate container a78deef9950c
```

we still end up with errors like

```
Step 37/54 : RUN cargo build --$PROFILE -p polkadot-runtime-common
 ---> Running in 9f65497b7c6d
   Compiling polkadot-runtime-common v0.7.17 (/polkadot/runtime/common)
error[E0432]: unresolved imports `primitives::Hash`, `primitives::parachain`
  --> runtime/common/src/attestations.rs:26:18
   |
26 | use primitives::{Hash, parachain::{AttestedCandidate, CandidateReceipt, Id as ParaId}};
   |                  ^^^^  ^^^^^^^^^ could not find `parachain` in `primitives`
   |                  |
   |                  no `Hash` in the root

```

This optimization has now consumed more dev time than it's worth. I'm
preserving it in git just in case, but it's time to simplify.

* Simplify Dockerfile: build everything at once

This removes the largest optimization performed, which is separating
the deps build from the project build. OTOH, it's a lot more likely
to actually work.

* copy each package individually into the container just before build

* Revert "copy each package individually into the container just before build"

This reverts commit 9a939553d680e3b1898e545ca8fe9d3f79d700bf.

The attempt didn't work, unfortunately.

* improve 2nd stage caching

* exclude more from the docker archive

This should reduce the number of spurious cache misses

* exclude .git from docker builds to reduce workspace size

* undo accidentally removing Cargo.lock

* Add flag which enables external RPC access to nodes

Also don't send root-level dotfiles to docker; this prevents
some spurious cache-busting.

* update Cargo.lock

* bump impl_version to placate CI